Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2019-12, with the labels that each got.

#90 Fix iframe downloads
  src/core/InsightContainer/index.js
  src/core/utils.js
  stories/container.stories.js
Labels: bug

#89 Standardize Tooltips + Fix some warnings
  src/core/ActionButton.js
  src/core/BarChart/BarLabel.js
  src/core/BulletChart/BulletBar.js
  src/core/BulletChart/index.js
  src/core/ComparisonBarChart.js
  src/core/EmbedDropDown.js
  src/core/Label.js
  src/core/LegendLabel.js
  src/core/NestedProportionalAreaChart/ScaledCircle.js
  src/core/NestedProportionalAreaChart/ScaledSquare.js
  src/core/PieChart/DonutTooltip.js
  src/core/PieChart/index.js
  src/core/ShareDropDown.js
  src/core/utils.js
  src/factory/ChartFactory.js
  src/factory/utils/aggregateData.js
  stories/chart.stories.js
  stories/container.stories.js
  stories/factory.stories.js
  stories/mapit.stories.js
Labels: bug, enhancement

#91 [Hotfix] Nested Area Data Label
  src/factory/ChartFactory.js
Labels: bug

#92 Of ChartFactory & Percent
  src/factory/ChartFactory.js
  src/factory/utils/aggregateData.js
  stories/factory.stories.js
Labels: bug, enhancement

#93 [Hotfix] Prioritise profile label for Nested Area Chart labels
  src/factory/ChartFactory.js
Labels: bug

#94 Make SHOW MORE/SHOW LESS button optional
  src/factory/ChartFactory.js
  stories/factory.stories.js
  yarn.lock
Labels: enhancement
