Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2019-10, with the labels that each got.

#60 v0.2 Setup
  .babelrc
  .browserslistrc
  .eslintrc.js
  package.json
  src/BarChart/index.js
  src/BulletChart/BulletBar.js
  src/BulletChart/index.js
  src/Chart.js
  src/ComparisonBarChart.js
  src/ContentLoader.js
  src/CustomContainer.js
  src/InsightContainer/Actions.js
  src/LineChart.js
  src/MapIt/index.js
  src/NestedProportionalAreaChart/HorizontalLegend.js
  src/NestedProportionalAreaChart/ScaledArea.js
  src/NestedProportionalAreaChart/ScaledCircle.js
  src/NestedProportionalAreaChart/ScaledSquare.js
  src/NestedProportionalAreaChart/VerticalLegend.js
  src/NestedProportionalAreaChart/index.js
  src/NumberVisuals.js
  src/PieChart/LegendLabel.js
  src/PieChart/PieLabel.js
  src/PieChart/index.js
  src/Tooltip.js
  src/styles/createTheme.js
  src/styles/createVictoryTheme.js
  stories/chart.stories.js
  stories/mapit.stories.js
  yarn.lock
Labels: bug, enhancement

#61 Reusable Insight Chart Container
  .eslintrc.js
  src/InsightContainer/Actions.js
  src/InsightContainer/Insight.js
  src/InsightContainer/index.js
  stories/container.stories.js
Labels: bug, enhancement

#65 Fix Chartfactory
  src/factory/ChartFactory.js
  stories/factory.stories.js
Labels: bug

#66 [Hotfix] makeStyles variant check
  src/core/InsightContainer/Insight.js
  src/core/InsightContainer/index.js
Labels: bug

#63 I Am Legend
  src/core/BarChart/index.js
  src/core/ComparisonBarChart.js
  src/core/Label.js
  src/core/LegendLabel.js
  src/core/LineChart.js
  src/core/PieChart/DonutLabel.js
  src/core/PieChart/LegendLabel.js
  src/core/PieChart/PieLabel.js
  src/core/PieChart/SharedEvents.js
  src/core/PieChart/Tooltip.js
  src/core/PieChart/index.js
  src/core/styles/createVictoryTheme.js
  src/core/utils.js
  stories/chart.stories.js
Labels: enhancement

#69 DownThemAll!
  src/core/ChartContainer/index.js
Labels: enhancement

#68 Freestyle [HURUStyle]
  src/core/BarChart/index.js
  src/core/ComparisonBarChart.js
  src/core/Label.js
  src/core/LegendLabel.js
  src/core/LineChart.js
  src/core/PieChart/index.js
  src/core/styles/createVictoryTheme.js
  src/core/styles/withVictoryTheme.js
  src/core/utils.js
  stories/chart.stories.js
  stories/container.stories.js
Labels: enhancement

#70 ... And then there were none
  src/core/BarChart/index.js
  src/core/BulletChart/BulletBar.js
  src/core/BulletChart/index.js
  src/core/ComparisonBarChart.js
  src/core/LineChart.js
  src/core/NestedProportionalAreaChart/HorizontalLegend.js
  src/core/NestedProportionalAreaChart/ScaledCircle.js
  src/core/NestedProportionalAreaChart/ScaledSquare.js
  src/core/NestedProportionalAreaChart/VerticalLegend.js
  src/core/NestedProportionalAreaChart/index.js
  src/core/PieChart/SharedEvents.js
  src/core/PieChart/index.js
  src/core/styles/createVictoryTheme.js
  stories/chart.stories.js
Labels: enhancement

#72 Fix variant styles
  src/core/InsightContainer/index.js
Labels: bug, enhancement
