Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2019-09, with the labels that each got.

#48 Create Insight charts container
  src/BlockLoader.js
  src/ContentLoader.js
  src/InsightContainer/Actions.js
  src/InsightContainer/index.js
  src/NumberVisuals.js
  src/TypographyLoader.js
  src/assets/icons/code.svg
  src/assets/icons/compare.svg
  src/assets/icons/download.svg
  src/assets/icons/network-connection.svg
  src/assets/icons/tablet-reader.svg
  src/index.js
  stories/common.js
  stories/insightcontainer.stories.js
Labels: enhancement

#46 Move Dropdown components inside chart container
  src/ChartContainer/DropDown.js
  src/ChartContainer/EmbedDropDown.js
  src/ChartContainer/EmbedPopup.js
  src/ChartContainer/InfoPopup.js
  src/ChartContainer/ShareDropDown.js
  src/ChartContainer/index.js
  src/ContentLoader.js
  src/index.js
  stories/container.stories.js
  stories/insightcontainer.stories.js
Labels: bug, enhancement

#51 Fix nested chart number format
  src/NestedProportionalAreaChart/HorizontalLegend.js
  src/NestedProportionalAreaChart/ScaledCircle.js
  src/NestedProportionalAreaChart/ScaledSquare.js
  src/NestedProportionalAreaChart/VerticalLegend.js
  src/NestedProportionalAreaChart/index.js
  stories/chart.stories.js
Labels: bug, enhancement

#52 Add text wrapping to VictoryLabel & Use it for Legend
  src/Label.js
  src/PieChart/LegendLabel.js
  src/PieChart/PieLabel.js
  src/PieChart/index.js
  stories/chart.stories.js
Labels: enhancement

#54 Style config + undefined props update
  src/InsightContainer/Actions.js
  src/InsightContainer/index.js
  src/NumberVisuals.js
  stories/container.stories.js
  stories/numbers.stories.js
Labels: bug

#56 Fix SVG Blockloader Breaking in Chrome
  package.json
  src/BarChart/BarLabel.js
  src/BlockLoader.js
  src/ChartContainer/index.js
  src/ContentLoader.js
  src/InsightContainer/index.js
  src/MapIt/index.js
  src/WrapLabel/index.js
  yarn.lock
Labels: bug

#55 Improve Share Dialog
  package.json
  src/ChartContainer/ShareDropDown.js
  src/ChartContainer/index.js
  stories/container.stories.js
  yarn.lock
Labels: dependencies, enhancement

#58 v0.1.11 Improvements
  src/ChartContainer/index.js
  src/MapIt/index.js
  src/PieChart/index.js
  stories/container.stories.js
Labels: bug

#59 Improve Insight Chart Container Download/Share Actions
  package.json
  src/InsightContainer/index.js
  yarn.lock
Labels: dependencies, enhancement
