Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2019-08, with the labels that each got.

#36 Set tootips as default label component for common charts
  src/BarChart.tsx
  src/LineChart.tsx
  src/NestedProportionalAreaChart/index.tsx
  src/PieChart/PieLabel.tsx
  src/PieChart/index.tsx
  stories/chart.stories.tsx
Labels: enhancement

#38 [Chore] Prepare for v0.1
  package.json
  src/ChartContainer/index.tsx
  src/MapIt.tsx
  stories/container.stories.tsx
  yarn.lock
Labels: bug

#39 Fix mapit too many reloads
  package.json
  src/MapIt/index.tsx
  src/MapIt/useDeepRef.ts
  stories/mapit.stories.tsx
  yarn.lock
Labels: bug, enhancement

#37 Add number visual card
  src/NumberVisuals/index.tsx
  src/Theme.ts
  src/index.ts
  stories/numbers.stories.tsx
Labels: enhancement

#42 Donut as the default Pie chart mode
  src/NestedProportionalAreaChart/ScaledCircle.js
  src/PieChart/index.js
  src/styles/createVictoryTheme.js
  stories/chart.stories.js
Labels: enhancement

#41 Remove scroll
  src/BarChart.js
  src/ChartContainer/index.js
  src/styles/createVictoryTheme.js
  stories/chart.stories.js
  stories/container.stories.js
Labels: enhancement

#43 Fix tickFormat & PropTypes
  src/BarChart.js
  src/BulletChart/BulletBar.js
  src/BulletChart/index.js
  src/Chart.js
  src/ComparisonBarChart.js
  src/CustomContainer.js
  src/LineChart.js
  src/NestedProportionalAreaChart/HorizontalLegend.js
  src/NestedProportionalAreaChart/ScaledCircle.js
  src/NestedProportionalAreaChart/ScaledSquare.js
  src/NestedProportionalAreaChart/VerticalLegend.js
  src/NumberVisuals.js
  src/PieChart/index.js
  src/WrapLabel/index.js
  stories/chart.stories.js
Labels: bug

#45 Donut chart enhancements
  src/PieChart/DonutLabel.js
  src/PieChart/LegendLabel.js
  src/PieChart/PieLabel.js
  src/PieChart/index.js
  src/styles/createVictoryTheme.js
  stories/chart.stories.js
Labels: enhancement
