Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2019-11, with the labels that each got.

#73 Allow population table conditions for fetching
  src/factory/useProfileLoader/queries.js
Labels: bug, enhancement

#74 Signed, Sealed, Delivered
  src/core/ChartContainer/index.js
  src/core/InsightContainer/Insight.js
  src/core/InsightContainer/index.js
  src/core/assets/logo.png
  src/core/utils.js
  stories/assets/dominion-logo.png
  stories/container.stories.js
Labels: dependencies, enhancement

#75 [Hotfix] Data Format & Tooltip
  src/core/Label.js
  src/core/LegendLabel.js
  src/core/PieChart/DonutTooltip.js
  src/core/PieChart/SharedEvents.js
  src/core/PieChart/index.js
  src/core/styles/createVictoryTheme.js
  src/core/utils.js
  src/factory/ChartFactory.js
  stories/chart.stories.js
  yarn.lock
Labels: dependencies, enhancement

#77 Hotfix useProfileLoader using wrong parent level and geo code details
  src/factory/useProfileLoader/index.js
Labels: bug

#78 Accept visual definition props
  src/core/BarChart/index.js
  src/core/ChartContainer/index.js
  src/factory/ChartFactory.js
  stories/container.stories.js
  stories/factory.stories.js
Labels: bug, enhancement

#79 [Hotfix] Chart container source could be "undefined"
  src/core/ChartContainer/index.js
  src/core/InsightContainer/index.js
Labels: bug

#80 Remove @material-ui/styles dependency
  package.json
  src/core/ChartContainer/DropDown.js
  src/core/ChartContainer/EmbedDropDown.js
  src/core/ChartContainer/ShareDropDown.js
  src/core/ChartContainer/index.js
  src/core/InsightContainer/Action/ActionButton.js
  src/core/InsightContainer/Action/index.js
  src/core/InsightContainer/Insight.js
  src/core/InsightContainer/index.js
  src/core/NumberVisuals.js
  src/core/styles/withVictoryTheme.js
  stories/common.js
  stories/theme.js
  yarn.lock
Labels: bug

#81 [Hotfix] Stubbon @material-ui/styles reference
  src/core/index.js
  src/factory/utils/aggregateData.js
  stories/chart.stories.js
  stories/container.stories.js
Labels: bug, dependencies

#83 [Hotfix] Default InsightChartContainer actions & their customizability
  src/core/InsightContainer/Action/index.js
  src/core/InsightContainer/index.js
  stories/container.stories.js
Labels: bug, enhancement

#82 Add forgotten chart description to insight chart container
  package.json
  src/core/ChartContainer/index.js
  src/core/InsightContainer/index.js
  stories/container.stories.js
  yarn.lock
Labels: dependencies, enhancement

#84 [Hotfix] SVG Components
  .babelrc
  package.json
  src/core/ChartContainer/index.js
  src/core/InsightContainer/Action/index.js
  yarn.lock
Labels: bug, dependencies, enhancement

#86 [Bug] Fix analysis link title prop
  src/core/InsightContainer/Insight.js
  stories/container.stories.js
Labels: bug

#87 Screenshot iframe Content on Download
  package.json
  public/chart-screenshot.png
  public/iframe.html
  src/core/utils.js
  stories/container.stories.js
Labels: enhancement
