Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2020-07, with the labels that each got.

#152 [HotFix] Snippets
  .eslintrc.js
  .storybook/addons.js
  .storybook/config.js
  .storybook/main.js
  .storybook/manager.js
  package.json
  packages/charts/package.json
  packages/charts/src/styles/createVictoryTheme.js
  packages/charts/src/utils/index.js
  packages/content/package.json
  packages/core/package.json
  packages/core/src/MapIt/index.js
  packages/core/src/Snippet/index.js
  stories/assets/cfa.png
  stories/card.stories.js
  stories/chart.stories.js
  stories/common.js
  stories/container.stories.js
  stories/factory.stories.js
  stories/mapit.stories.js
  stories/snippet.stories.js
  yarn.lock
Labels: bug, dependencies, enhancement

#153 [HotFix] Dependencies
  package.json
  packages/content/package.json
  packages/core/package.json
  yarn.lock
Labels: dependencies, enhancement

#154 [HotFix] ChartFactory NumberVisuals description
  packages/charts/src/ChartFactory.js
  packages/charts/src/NumberVisuals.js
Labels: bug

#158 [HotFix] Processed data array push
  packages/charts/src/ChartFactory.js
  packages/core/src/Card/HURUmapChart.js
Labels: bug

#159 Fix line label
  packages/charts/src/ChartFactory.js
  packages/charts/src/LineChart.js
  packages/core/src/Card/HURUmapChart.js
  stories/theme.js
Labels: bug, enhancement

#160 [Hotfix] Fix deep merge + parts
  packages/charts/src/ChartFactory.js
  packages/charts/src/LineChart.js
  stories/theme.js
Labels: bug
