Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2020-03, with the labels that each got.

#117 Use react-pdf instead of @mikecousins/react-pdf
  package.json
  src/core/PDFDataContainer.js
  yarn.lock
Labels: bug, dependencies

#119 Use innerHTML for html source
  src/cms/attributes.js
  src/cms/index.js
  src/components/Card/index.js
Labels: bug

#120 [Hotfix] Pdf stories + bug
  package.json
  src/core/PDFDataContainer.js
  stories/pdfcontainer.stories.js
  yarn.lock
Labels: bug, enhancement

#114 Fix card component to be used in data by topic
  src/components/Card/ChartContainer.js
  src/components/Card/FlourishChart.js
  src/components/Card/HURUmapChart.js
  src/components/Card/index.js
  src/core/ActionButton.js
  src/core/ActionsModal/DownloadPanel.js
  src/core/ActionsModal/EmbedPanel.js
  src/core/ActionsModal/SharePanel.js
  src/core/ActionsModal/index.js
  src/core/BarChart/index.js
  src/core/ChartContainer.js
  src/core/DataTable/index.js
  src/core/DropDown.js
  src/core/EmbedDropDown.js
  src/core/InsightContainer/Action/index.js
  src/core/InsightContainer/Insight.js
  src/core/InsightContainer/index.js
  src/core/MapIt/index.js
  src/core/NumberVisuals.js
  src/core/ShareDropDown.js
  src/core/Snippet/Actions.js
  src/core/Snippet/Button.js
  src/core/Snippet/index.js
  src/core/styles/makeStyles.js
Labels: enhancement

#118 Split computation of max label dimension to avoid many hooks being invoked
  src/core/BarChart/index.js
  src/core/WrapLabel/index.js
  src/core/WrapLabel/wrapSVGText.js
Labels: enhancement

#122 Share/+Download - Fix convert to domToPng
  packages/core/src/ChartContainer.js
  packages/core/src/InsightContainer/index.js
  packages/core/src/utils.js
  stories/assets/dominion-logo.png
  stories/assets/hurumap-logo-white.png
  stories/card.stories.js
  stories/container.stories.js
Labels: bug

#124 Fix undefined Indicator type
  packages/content/src/dataProps.js
Labels: bug

#125 Math Is In Session - Fix show more and show less data calculations
  packages/charts/src/BarChart/index.js
  packages/charts/src/ChartFactory.js
  packages/charts/src/WrapLabel/wrapSVGText.js
  stories/container.stories.js
  stories/factory.stories.js
Labels: bug, enhancement

#126 Chore/lerna + yarn workspace
  lerna.json
  package.json
  packages/charts/package.json
  packages/content/package.json
  packages/core/package.json
  yarn.lock
Labels: bug, dependencies, enhancement

#128 Snippet Dialog
  packages/core/src/ActionsModal/DownloadPanel.js
  packages/core/src/ActionsModal/EmbedPanel.js
  packages/core/src/ActionsModal/SharePanel.js
  packages/core/src/ActionsModal/index.js
Labels: bug, enhancement

#127 Snippet Title
  packages/core/src/Snippet/Actions.js
  packages/core/src/Snippet/index.js
  stories/snippet.stories.js
Labels: bug, enhancement

#129 Fix use correct label dimmension for padding
  packages/charts/src/BarChart/index.js
  packages/charts/src/ChartFactory.js
  packages/charts/src/WrapLabel/wrapSVGText.js
  stories/card.stories.js
  stories/container.stories.js
  stories/theme.js
Labels: bug
