Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2020-04, with the labels that each got.

#131 Grouped Data Legend
  packages/charts/src/BarChart/index.js
  packages/charts/src/ChartFactory.js
  packages/charts/src/LegendLabel.js
  packages/charts/src/LineChart.js
  packages/charts/src/PieChart/DonutTooltip.js
  packages/charts/src/PieChart/index.js
  packages/charts/src/WrapLabel/wrapSVGText.js
  packages/charts/src/styles/createVictoryTheme.js
  packages/charts/src/utils.js
  stories/chart.stories.js
  stories/factory.stories.js
Labels: bug, enhancement, feature

#132 Ensure data value x is always a number
  packages/charts/src/ChartFactory.js
  packages/charts/src/WrapLabel/wrapSVGText.js
Labels: bug

#130 Fix aggregate data
  .eslintrc.js
  README.md
  package.json
  packages/charts/jest.config.js
  packages/charts/jestBabelTransform.js
  packages/charts/package.json
  packages/charts/src/utils/aggregateData.js
  packages/charts/tests/aggregate.test.js
  yarn.lock
Labels: bug, enhancement, feature

#133 Resolve modules from production and development
  babel.config.js
Labels: bug

#135 Fix/theme defaults
  packages/charts/src/styles/createVictoryTheme.js
Labels: bug

#136 Fix/legend wrapping
  packages/charts/src/BarChart/index.js
  packages/charts/src/LegendLabel.js
  packages/charts/src/LegendPoint.js
  packages/charts/src/PieChart/index.js
  packages/charts/src/styles/createVictoryTheme.js
  packages/charts/src/utils.js
  stories/card.stories.js
  stories/theme.js
Labels: bug

#137 Legendary - Responsive legend!
  packages/charts/src/BarChart/index.js
  packages/charts/src/ChartFactory.js
  packages/charts/src/Legend.js
  packages/charts/src/LegendLabel.js
  packages/charts/src/LegendPoint.js
  packages/charts/src/LineChart.js
  packages/charts/src/PieChart/index.js
  packages/charts/src/styles/createVictoryTheme.js
  packages/charts/src/utils.js
  stories/theme.js
Labels: bug, enhancement

#138 [Hotfix] Enable PDF.js worker
  packages/core/src/PDFDataContainer.js
Labels: bug

#139 Fix/aggregate
  packages/charts/src/ChartFactory.js
  packages/charts/src/utils/aggregateData.js
  packages/charts/tests/aggregate.test.js
  packages/core/src/Card/HURUmapChart.js
  stories/card.stories.js
  stories/factory.stories.js
Labels: bug, enhancement
