Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2020-05, with the labels that each got.

#144 [HotFix] Embed Dropdown class props
  packages/core/src/ChartContainer.js
  packages/core/src/GroupActionsDropDown.js
Labels: bug

#143 Mapit Geo styles Enhancement
  packages/core/src/MapIt/index.js
  packages/core/src/index.js
  packages/core/src/useGeoIndexLoader/buildGeoIndexQuery.js
  packages/core/src/useGeoIndexLoader/index.js
  packages/core/src/useProfileLoader/index.js
  stories/mapit.stories.js
Labels: enhancement

#145 [HotFix] Filter iframe toPng
  package.json
  packages/core/src/utils/index.js
  yarn.lock
Labels: bug, dependencies

#146 Vulnerability score on map Tooltip
  packages/core/src/MapIt/index.js
  packages/core/src/useGeoIndexLoader/buildGeoIndexQuery.js
  packages/core/src/useGeoIndexLoader/index.js
  packages/core/src/useProfileLoader/index.js
  stories/mapit.stories.js
Labels: enhancement

#147 [HotFix] Typecheck window for SSR
  packages/core/src/GroupActionsDropDown.js
  packages/core/src/ShareDropDown.js
Labels: bug

#148 [HotFix] Wrong scoreField in buildGeoIndexQuery
  packages/core/src/useGeoIndexLoader/index.js
Labels: bug
