Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2020-02, with the labels that each got.

#109 Peek A Boo, I see you 👀 Fix Hide Show More button if chart fits
  src/core/InsightContainer/index.js
  src/factory/ChartFactory.js
Labels: bug

#110 Group data for line charts when defined
  src/factory/ChartFactory.js
Labels: bug

#111 [Hotfix] Snippet Share
  package.json
  src/core/ActionsModal/index.js
  src/core/Snippet/index.js
  yarn.lock
Labels: bug, dependencies

#112 [HotFix] PieChart donut label data selection
  src/core/PieChart/index.js
  stories/chart.stories.js
Labels: bug, enhancement

#113 Fix/label width overflow
  src/components/Card/HURUmapChart.js
  src/components/Card/index.js
  src/core/BarChart/index.js
  src/core/Chart.js
  src/core/NumberVisuals.js
  src/core/WrapLabel/index.js
  src/core/WrapLabel/wrapSVGText.js
  src/core/utils.js
  src/factory/ChartFactory.js
  stories/theme.js
Labels: bug, enhancement

#116 Hydrate indicator widget
  package.json
  src/cms/attributes.js
  src/cms/index.js
  src/components/Card/ChartContainer.js
  src/components/Card/index.js
  src/core/PDFDataContainer.js
  src/core/assets/icons/left-arrow.svg
  src/core/assets/icons/right-arrow.svg
  yarn.lock
Labels: enhancement
