Repository CodeForAfrica/HURUmap-UI, pull requests merged in 2020-01, with the labels that each got.

#96 [Hotfix] chart `id` in ChartFactory
  src/factory/ChartFactory.js
  stories/factory.stories.js
Labels: bug

#95 Refactor Profile Loader
  src/factory/useProfileLoader/index.js
  src/factory/useProfileLoader/queries.js
  src/factory/utils/index.js
  src/factory/utils/visualLoader.js
  yarn.lock
Labels: enhancement

#97 [Hotfix] Theme proptypes on chartfactory
  src/factory/ChartFactory.js
Labels: bug

#99 Lights, Camera, Action!
  src/core/ActionsModal/DownloadPanel.js
  src/core/ActionsModal/EmbedPanel.js
  src/core/ActionsModal/SharePanel.js
  src/core/ActionsModal/TabPanel.js
  src/core/ActionsModal/index.js
  src/core/Card/Actions.js
  src/core/Card/Button.js
  src/core/Card/index.js
  stories/card.stories.js
Labels: enhancement

#102 ChartContainer variant support
  src/core/ChartContainer.js
  src/core/EmbedDropDown.js
  src/core/ShareDropDown.js
  stories/container.stories.js
Labels: bug, enhancement

#103 Fit any image in card to max 100% width
  src/core/Card/index.js
Labels: bug

#101 Feature reusable cms + components library folder
  .gitignore
  package.json
  src/cms/attributes.js
  src/cms/index.js
  src/components/Card/ChartContainer.js
  src/components/Card/FlourishChart.js
  src/components/Card/HURUmapChart.js
  src/components/Card/index.js
  src/components/index.js
  src/components/propTypes.js
  src/components/utils/index.js
  src/core/ActionsModal/index.js
  src/core/ChartContainer.js
  src/core/InsightContainer/index.js
  src/core/Snippet/Actions.js
  src/core/Snippet/Button.js
  src/core/Snippet/index.js
  src/core/index.js
  src/core/utils.js
  src/factory/ChartFactory.js
  src/factory/useProfileLoader/buildProfileQuery.js
  src/factory/useProfileLoader/index.js
  src/factory/useVisualLoader/buildVisualsQuery.js
  src/factory/useVisualLoader/index.js
  src/factory/utils/assignQueryAlias.js
  src/factory/utils/index.js
  stories/card.stories.js
  stories/snippet.stories.js
  yarn.lock
Labels: enhancement

#104 [Hotfix] Fix data attribute props and add ability to get the deprecated props
  src/cms/attributes.js
  src/cms/index.js
Labels: bug, enhancement

#106 [Hotfix] ChartFactory BarChart padding
  src/factory/ChartFactory.js
Labels: bug

#105 HURUShare
  src/components/Card/HURUmapChart.js
  src/components/Card/index.js
  src/components/utils/index.js
  stories/card.stories.js
Labels: bug, enhancement

#107 [Hotfix] Use indicatorId on searchParam
  src/components/utils/index.js
Labels: bug
